name: Lint HTML Game

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install linters
        run: npm install -g htmlhint stylelint eslint
      - name: Lint HTML
        run: |
          htmlhint index.html
          stylelint styling.css
          eslint jquery.js --env browser

